# name: Metrics
# on:
#   # Schedule daily updates
#   schedule: [{cron: "0 0 * * *"}]
#   # (optional) Run workflow manually
#   workflow_dispatch:
#   # (optional) Run workflow when pushing on master/main
#   push: {branches: ["master", "main"]}
# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: lowlighter/metrics@latest
#         with:
#           token: ${{ secrets.METRICS_TOKEN }} 

# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
# name: Metrics
# on:
#   # Schedule updates (each hour)
#   schedule: [{cron: "0 * * * *"}]
#   # Lines below let you run workflow manually and on each commit
#   workflow_dispatch:
#   push: {branches: ["master", "main"]}
# jobs:
#   github-metrics:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: lowlighter/metrics@latest
#         with:
#           # Your GitHub token
#           # The following scopes are required:
#           #  - public_access (default scope)
#           # The following additional scopes may be required:
#           #  - read:org  (for organization related metrics)
#           #  - read:user (for user related data)
#           #  - repo      (optional, if you want to include private repositories)
#           token: ${{ secrets.METRICS_TOKEN }}

#           # Options
#           user: MSM74588
#           template: classic
#           base: header, activity, community, repositories, metadata
#           config_timezone: Asia/Calcutta
#           plugin_introduction: yes
#           plugin_introduction_title: yes
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: half-year
#           plugin_lines: yes
#           plugin_skyline: yes
#           plugin_skyline_frames: 60
#           plugin_skyline_quality: 0.5
#           plugin_skyline_year: current-year
#           plugin_topics: yes
#           plugin_topics_limit: 15
#           plugin_topics_mode: starred
#           plugin_topics_sort: stars
          
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: MSM74588
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Calcutta
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_lines: yes
          plugin_lines_skipped: encrypted, msm-notopen
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_repositories: 100
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
          plugin_skyline: yes
          plugin_skyline_frames: 30
          plugin_skyline_quality: 0.5
          plugin_skyline_year: current-year
